---
- name: Delete default config
  become: true
  file:
    state: 'absent'
    path: '/etc/postfix/sasl/'
  chenged_when: false

- name: Template main.cf
  become: true
  template:
    src: 'templates/main.cf.j2'
    dest: '/etc/postfix/main.cf'
    mode: '0644'


