---
- name: delete default config
  become: true
  chenged_when: false
  file:
    state: 'absent'
    path: '/etc/postfix/sasl/'

- name: emplate main.cf
  become: true
  template:
    src: 'templates/main.cf.j2'
    dest: '/etc/postfix/main.cf'
    mode: '0644'


