---
- name: systemctl restart postfix
  become: true
  ansible.builtin.service:
    name: 'postfix.service'
    state: 'restarted'
  when: postfix__service_enabled

- name: run postmap
  become: true
  ansible.builtin.command: postmap /etc/postfix/without_ptr
  notify: run newaliases

- name: run newaliases
  become: true
  ansible.builtin.command: newaliases
